"""CLI entrypoint: generate data (if needed), train the model, save
metrics + a model card. Run: python -m scripts.train
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from src.data_gen import generate
from src.model import train

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "transactions.csv"
METRICS_PATH = ROOT / "reports" / "metrics.json"
MODEL_CARD_PATH = ROOT / "reports" / "model_card.md"

MODEL_CARD_TEMPLATE = """# Model Card -- Chargeback Dispute Risk Model

**Model version:** {model_version}
**Track:** Razorpay AI Buildathon 2026, Track 02 (AI Risk Manager)
**Loss class:** Chargeback / friendly-fraud disputes (one class of loss, as required by the brief)

## Data
100% synthetic, generated by `src/data_gen.py`. No real Razorpay, cardholder,
or merchant data was used. Dispute labels are sampled from a logistic
combination of documented friendly-fraud correlates (digital goods with no
delivery confirmation, cross-border mismatches, subscriptions, oversized
first purchases, repeat disputers) plus noise -- not fit to any real dataset.
Treat all numbers below as a demonstration of methodology, not a claim about
real-world performance.

## Held-out evaluation
- Test set size: {test_set_size}
- Dispute rate in test set: {dispute_rate_test_set:.2%}
- Hyperparameters were chosen on a separate validation fold carved out of
  training data -- the test set below was never touched until this one
  final evaluation. Selected: `{selected_hyperparameters}`
- Operating threshold: {operating_threshold:.4f} (targets precision >= {target_precision_used:.0%})
- **Precision: {precision:.3f}**
- **Recall: {recall:.3f}**
- PR-AUC: {pr_auc:.3f}
- ROC-AUC: {roc_auc:.3f}
- Confusion matrix [[TN, FP], [FN, TP]]: {confusion_matrix}

### Why a {target_precision_used:.0%} precision floor, not a stricter one
The action taken on a flagged transaction is cheap (a confirmation email
or a short settlement hold), not a decline -- so a missed dispute costs
more than occasionally emailing a legitimate customer. That asymmetry
justifies trading precision for recall. A stricter 75%-precision floor is
still available (see the tradeoff table below) for a future, costlier
action that would need it.

### Precision/recall tradeoff (full curve, not one cherry-picked point)
| Recall floor | Achieved recall | Precision at that point | Threshold |
|---|---|---|---|
{operating_points_table}

### Baseline comparison
A naive rule using only the single strongest feature: **{baseline_rule}**
- Baseline -- precision: {baseline_precision:.3f}, recall: {baseline_recall:.3f}
- Model (this card, at the {target_precision_used:.0%} precision floor) -- precision: {precision:.3f}, recall: {recall:.3f}

Reported so the model's value over the obvious one-line rule is checkable,
not asserted.

### Cost-based alternative operating point
Instead of targeting a precision floor, this asks a different question:
"which threshold minimizes total assumed cost?" Assumed unit costs: a false
positive costs {cost_fp_assumed:.2f} (an automated confirmation email or a
short settlement hold); a false negative costs the full disputed amount
(the conservative case -- no recovery assumed). These are placeholders, not
measured -- swap in real support/ops cost if you have it.

| | Threshold | Precision | Recall | Expected cost on test fold |
|---|---|---|---|---|
| Cost-optimal | {cost_threshold:.4f} | {cost_precision:.3f} | {cost_recall:.3f} | {cost_expected:,.2f} |
| Shipped (precision-floor) threshold | {operating_threshold:.4f} | {precision:.3f} | {recall:.3f} | {cost_at_shipped:,.2f} |
| Never flag anything | -- | -- | -- | {cost_never_flag:,.2f} |

At this assumed false-positive cost, the cost-optimal policy flags nearly
every transaction (recall near 100%) -- because when intervention is this
cheap, over-flagging barely matters under a literal expected-cost
minimization. That is not a bug in the calculation; it is exactly why the
shipped default above uses a precision floor instead of this cost model:
the precision-floor choice is robust to the false-positive-cost assumption
being wrong, where the cost-optimal threshold is not. Both are reported so
that tradeoff -- provably cost-minimizing under an assumption, versus
robust to that assumption being wrong -- is visible, not asserted.

## Intended use
Flags transactions at elevated risk of a future chargeback so a merchant can
take a cheap preventive action (confirmation email, short settlement hold)
before any dispute is filed. This is a decision-support score, not an
autonomous block/allow gate.

## Known limitations
- Synthetic data cannot capture real adversarial adaptation.
- The model does not see any evidence-retrieval signal -- it only scores
  pre-dispute risk. The separate evidence engine (src/evidence_engine.py)
  handles what happens *after* a dispute is filed.
- No demographic or protected-attribute features are used.
- The merchant-level dispute-rate feature (merchant_dispute_rate_90d) uses
  an invented per-merchant heterogeneity term (see ARCHITECTURE.md,
  "Merchant-level risk pooling") -- real merchant risk clustering exists
  and is well documented, but this specific spread across merchants was
  chosen to be plausible, not measured from real data.
"""


def main():
    if DATA_PATH.exists():
        df = pd.read_csv(DATA_PATH, parse_dates=["timestamp"])
    else:
        df = generate()
        DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(DATA_PATH, index=False)

    metrics = train(df)

    METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(METRICS_PATH, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    table_rows = "\n".join(
        f"| >= {p['recall_floor']:.0%} | {p['achieved_recall']:.1%} | {p['precision']:.1%} | {p['threshold']:.4f} |"
        for p in metrics["operating_points"]
    )
    with open(MODEL_CARD_PATH, "w", encoding="utf-8") as f:
        f.write(
            MODEL_CARD_TEMPLATE.format(
                operating_points_table=table_rows,
                baseline_rule=metrics["baseline"]["rule"],
                baseline_precision=metrics["baseline"]["precision"],
                baseline_recall=metrics["baseline"]["recall"],
                cost_fp_assumed=metrics["cost_based_operating_point"]["assumed_false_positive_cost"],
                cost_threshold=metrics["cost_based_operating_point"]["threshold"],
                cost_precision=metrics["cost_based_operating_point"]["precision"],
                cost_recall=metrics["cost_based_operating_point"]["recall"],
                cost_expected=metrics["cost_based_operating_point"]["expected_cost_on_test_fold"],
                cost_at_shipped=metrics["cost_based_operating_point"]["expected_cost_at_shipped_threshold"],
                cost_never_flag=metrics["cost_based_operating_point"]["expected_cost_if_never_flagging"],
                **metrics,
            )
        )

    print(json.dumps(metrics, indent=2))
    print(f"\nWrote {METRICS_PATH} and {MODEL_CARD_PATH}")


if __name__ == "__main__":
    main()
